#-------------------------------
# General Site Settings
title: Mangila
logo: '/images/logo.svg' # You can add own logo. For example '/images/logo.png'.
description: Minimalistic and Elegant Theme
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# Author Settings
author:
  name: Karen Millen
  bio: Hi, my name is Karen Millen. Tellus vel sodales condimentum, urna ex tincidunt nisl, luctus gravida nunc nisi at risus. Nam eget bibendum odio. Nam dignissim odio quis ipsum tristique, at luctus ex volutpat. Maecenas ullamcorper imperdiet.
  image: '/images/01.jpg'
  avatar: '/images/15.jpg'

# Example of adding a new link to the section author - {link: "https://github.com"}
author-social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}


#-------------------------------
# Hero Settings
hero:
  hero__image: '/images/01.jpg'
  hero__title: Welcome to Mangila
  hero__description: Thoughts, stories and ideas.


#-------------------------------
# Gallery section
gallery:
  images:
    - alt: 'Minimalism'
      url: '/images/17.jpg'
    - alt: 'Minimalism'
      url: '/images/07.jpg'
    - alt: 'Minimalism'
      url: '/images/08.jpg'
    - alt: 'Minimalism'
      url: '/images/22.jpg'


#-------------------------------
# Footer section
# Example of adding a new link to the footer - {icon: "ion-logo-github", link: "https://github.com"}
# Other icons can be found at https://ionicons.com
social:
- {icon: "ion-logo-twitter", link: "https://twitter.com"}
- {icon: "ion-logo-facebook", link: "https://facebook.com"}
- {icon: "ion-logo-dribbble", link: "https://dribbble.com"}
- {icon: "ion-logo-instagram", link: "https://instagram.com"}
- {icon: "ion-logo-pinterest", link: "https://pinterest.com"}
- {icon: "ion-logo-github", link: "https://github.com"}


#-------------------------------
# Comment Section (Disqus)
disqus-identifier: mr-brown # add your shortname for Disqus Comment. For example mr-brown


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp:
  mailchimp-identifier: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# NOTE
# If you don't want to use the subscribe section, just remove or comment out these lines true.


#-------------------------------
# Contant form Settings
contact:
  email: your@email.com # Add your email for contant form
  description: Mangila comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want. # Add a description of your form

# NOTE
# Mangila comes with a built-in contact form, that you can use with Formspree service to handle up to 50 submissions per month for free. You could also easily switch to another contact form service if you want.


#-------------------------------
# Build settings
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll/tagging

paginate: 9
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

sass:
  sass_dir: _sass
  style: compressed